# Generated by Django 3.2.4 on 2021-06-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0002_alter_link_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('from_site', models.URLField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=8, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('time_for_opener', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='shortener.link')),
            ],
        ),
    ]
