# Generated by Django 3.2.4 on 2021-06-27 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkopening',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2021, 6, 27, 15, 29, 50, 28414, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
