# Generated by Django 3.2.4 on 2021-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(verbose_name='Исходная ссылка')),
                ('shorted_link_code', models.CharField(max_length=255, unique=True, verbose_name='Код сокращенной ссылки')),
                ('secret_key', models.CharField(max_length=455, unique=True, verbose_name='Секретный ключ')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/%Y/%m/%d', verbose_name='QR Код')),
            ],
        ),
    ]
