# Generated by Django 3.2.4 on 2021-06-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original',
            field=models.URLField(verbose_name='Исходная ссылка'),
        ),
    ]
